using Test
using BeautifulAlgorithms

include("test_gradient_descent.jl")
include("test_stochastic_gradient_descent.jl")
include("test_neural_network.jl")
include("test_multi_layer_neural_network.jl")
include("test_loss_functions.jl")
include("test_distance_functions.jl")
include("test_nearest_neighbor.jl")
include("test_k_nearest_neighbors.jl")
include("test_k_means_clustering.jl")
include("test_em_algorithm.jl")
include("test_linear_regression.jl")
include("test_radial_basis_regression.jl")
include("test_cross_entropy_method.jl")
include("test_finite_difference_methods.jl")
include("test_simulated_annealing.jl")
include("test_twiddle.jl")
include("test_newtons_method.jl")
include("test_gaussian_process.jl")
include("test_gaussian_process_kernels.jl")
include("test_thompson_sampling.jl")
include("test_particle_filter.jl")
include("test_value_iteration.jl")
include("test_branch_and_bound.jl")
include("test_monte_carlo_tree_search.jl")
include("test_huffman_coding.jl")
include("test_hailstone.jl")
include("test_bubble_sort!.jl")
include("test_merge_sort.jl")
include("test_insertion_sort!.jl")
include("test_bogo_sort!.jl")
include("test_quine.jl")
